name: "📱 Android Compatibility Report"
description: Report an issue with an Android app that happens only when AdGuard is ON
title: "[Android]: <App Name>"
labels: ["android", "compatibility"]
body:
  - type: markdown
    attributes:
      value: |
        ### Submission Guidelines
        Please ensure you have followed the [Troubleshooting Guide](https://github.com/your-repo#how-to-troubleshoot).
        * Use this form only if the app malfunctions due to AdGuard's interception (e.g., connection errors, SSL issues).
        * For missed ads or website breakage, please use the [AdguardFilters](https://github.com/AdguardTeam/AdguardFilters) repository.

  - type: input
    id: app_name
    attributes:
      label: Application Name
      placeholder: "e.g., Netflix, WhatsApp, PayPal"
    validations:
      required: true

  - type: input
    id: package_id
    attributes:
      label: Application Package ID
      placeholder: "e.g., com.netflix.mediaclient"
      description: "You can find this in AdGuard App Management or on the Play Store URL."
    validations:
      required: true

  - type: dropdown
    id: diagnosis_result
    attributes:
      label: Troubleshooting Result
      description: Which step resolved the issue during your testing?
      options:
        - "Disabling HTTPS filtering (Suggests SSL Pinning)"
        - "Adding to QUIC bypass (Suggests QUIC-related playback/loading issues)"
        - "Disabling 'Route traffic' (Suggests low-level conflict)"
        - "Excluding IP ranges (Suggests connection/gateway issues)"
        - "Other / Not sure"
    validations:
      required: true

  - type: dropdown
    id: suggested_list
    attributes:
      label: Suggested Configuration List
      description: Based on your findings, which list should be updated?
      options:
        - "filter_traffic_exclusions.json (Disable routing)"
        - "block_ads_exclusions.json (Disable ad blocking)"
        - "filter_https_traffic_exclusions.json (Disable HTTPS filtering)"
        - "quic_pkg_exclusions.txt (Allow QUIC traffic)"
        - "pkg_exclusions.txt (Low-level exclusion)"
        - "ipv4_routes_exclusions.txt (IP exclusion)"
        - "I am not sure, please investigate"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Description of the Problem
      placeholder: "Describe what happens (e.g., 'App says No Internet Connection', 'Videos won't play', etc.)"
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Final Checks
      options:
        - label: "I have confirmed that disabling the Tracking Protection or specific filters did NOT fix the issue."
          required: true
        - label: "I am using the default filtering settings for this application."
          required: true

  - type: markdown
    attributes:
      value: "Thank you for your report! Our team will review the compatibility status for this Package ID."